/**
 * Repo-level capture: the hook files `assert init --repo` commits so hosts
 * that read hooks from the repository capture every session on it, with no
 * org-level install. Verified in cloud sessions for Claude Code
 * (`.claude/settings.json`), Cursor cloud agents (`.cursor/hooks.json`) and
 * Devin (`.devin/hooks.v1.json`); Codex reads `.codex/hooks.json` locally.
 *
 * Every hook runs `.assert/hook.sh`, a shim that installs the CLI into
 * `~/.assert` on first use, so a fresh cloud container needs nothing else.
 * All writers merge into existing files: foreign hooks and settings are kept,
 * prior Assert hooks are replaced, and re-running changes nothing.
 */

import * as fs from 'fs';
import * as path from 'path';
import { DEVIN_HOOK_EVENTS } from './plugins';

export const SHIM_PATH = '.assert/hook.sh';

const CLAUDE_EVENTS = ['SessionStart', 'SessionEnd', 'Stop', 'PreToolUse', 'PostToolUse', 'UserPromptSubmit'];
const CODEX_EVENTS = ['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PostToolUse', 'Stop'];
const CURSOR_EVENTS = [
  'sessionStart',
  'sessionEnd',
  'stop',
  'preToolUse',
  'postToolUse',
  'beforeSubmitPrompt',
  'afterAgentResponse',
  'afterFileEdit',
];

/** Marker every Assert hook command carries, so merges can find prior ones. */
const MARKER = '/.assert/hook.sh';

export function generateShim(version: string): string {
  return `#!/bin/sh
# Assert capture hook — generated by \`assert init --repo\` (v${version}). Do not edit.
# Runs \`assert hook <agent> <event>\` with the hook payload on stdin, installing
# the CLI into ~/.assert on first use so fresh cloud containers need nothing
# else. Exits 0 whenever capture is unavailable: it never fails a tool call.
# https://github.com/Assert-Labs/cli
set -u
home="\${ASSERT_HOME:-$HOME/.assert}"
version="\${ASSERT_CLI_VERSION:-${version}}"
cli="$home/npm/node_modules/@assertlabs/cli/bin/assert.js"

node_bin=""
if command -v node >/dev/null 2>&1; then
  node_bin=$(command -v node)
else
  for candidate in /usr/local/bin/node /usr/bin/node /opt/homebrew/bin/node \\
    "$HOME"/.nvm/versions/node/*/bin/node /opt/node*/bin/node "$HOME"/.volta/bin/node; do
    if [ -x "$candidate" ]; then node_bin=$candidate; break; fi
  done
fi
[ -n "$node_bin" ] || exit 0

if [ ! -f "$cli" ]; then
  lock="$home/.installing"
  if mkdir -p "$home" && mkdir "$lock" 2>/dev/null; then
    npm_bin="$(dirname "$node_bin")/npm"
    [ -x "$npm_bin" ] || npm_bin=npm
    "$npm_bin" install --silent --no-audit --no-fund --prefix "$home/npm" "@assertlabs/cli@$version" >/dev/null 2>&1
    rmdir "$lock" 2>/dev/null
  else
    # Another hook is installing; wait for it rather than racing npm.
    i=0
    while [ ! -f "$cli" ] && [ $i -lt 120 ]; do sleep 0.5; i=$((i + 1)); done
  fi
  [ -f "$cli" ] || exit 0
fi

exec "$node_bin" "$cli" hook "$@"
`;
}

type Hook = { type?: string; command?: string; [k: string]: unknown };
type Group = { matcher?: string; hooks?: Hook[]; [k: string]: unknown };

function parseObject(text: string | null): Record<string, unknown> {
  try {
    const value = text && text.trim() ? JSON.parse(text) : {};
    return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
  } catch {
    return {};
  }
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

const isOurs = (hook: Hook) => typeof hook.command === 'string' && hook.command.includes(MARKER);

/** Merge Claude-shaped groups (`[{ hooks: [...] }]`) for one event. */
function mergeGroups(existing: unknown, command: string, timeout?: number): Group[] {
  const groups = Array.isArray(existing) ? (existing as Group[]) : [];
  const kept = groups
    .map((g) => ({ ...g, hooks: (g.hooks ?? []).filter((h) => !isOurs(h)) }))
    .filter((g) => g.hooks.length > 0);
  kept.push({ hooks: [{ type: 'command', command, ...(timeout ? { timeout } : {}) }] });
  return kept;
}

/** `.claude/settings.json`: hooks merged under the `hooks` key, rest untouched. */
export function upsertClaudeSettings(existing: string | null): string {
  const settings = parseObject(existing);
  const hooks = (settings.hooks && typeof settings.hooks === 'object' ? settings.hooks : {}) as Record<string, unknown>;
  for (const event of CLAUDE_EVENTS) {
    hooks[event] = mergeGroups(hooks[event], `"$CLAUDE_PROJECT_DIR${MARKER}" claude-code ${event}`);
  }
  settings.hooks = hooks;
  return json(settings);
}

/** `.devin/hooks.v1.json`: the hooks object is the whole file. */
export function upsertDevinHooks(existing: string | null): string {
  const hooks = parseObject(existing);
  for (const event of DEVIN_HOOK_EVENTS) {
    hooks[event] = mergeGroups(hooks[event], `"$DEVIN_PROJECT_DIR${MARKER}" devin ${event}`, 30);
  }
  return json(hooks);
}

/** `.codex/hooks.json`: Claude's shape under a `hooks` key; runs from the repo root. */
export function upsertCodexHooks(existing: string | null): string {
  const file = parseObject(existing);
  const hooks = (file.hooks && typeof file.hooks === 'object' ? file.hooks : {}) as Record<string, unknown>;
  for (const event of CODEX_EVENTS) {
    hooks[event] = mergeGroups(hooks[event], `.${MARKER} codex ${event}`);
  }
  file.hooks = hooks;
  return json(file);
}

/** `.cursor/hooks.json`: `{ version: 1, hooks: { event: [{ command }] } }`, run from the repo root. */
export function upsertCursorHooks(existing: string | null): string {
  const file = parseObject(existing);
  const hooks = (file.hooks && typeof file.hooks === 'object' ? file.hooks : {}) as Record<string, unknown>;
  for (const event of CURSOR_EVENTS) {
    const entries = Array.isArray(hooks[event]) ? (hooks[event] as Hook[]) : [];
    hooks[event] = [...entries.filter((h) => !isOurs(h)), { command: `.${MARKER} cursor ${event}` }];
  }
  return json({ version: 1, ...file, hooks });
}

/** Write every repo hook file into `gitRoot`; returns the paths written. */
export function installRepoHooks(gitRoot: string, version: string): string[] {
  const read = (rel: string): string | null => {
    try {
      return fs.readFileSync(path.join(gitRoot, rel), 'utf-8');
    } catch {
      return null;
    }
  };
  const files: Array<[string, string, number?]> = [
    [SHIM_PATH, generateShim(version), 0o755],
    ['.claude/settings.json', upsertClaudeSettings(read('.claude/settings.json'))],
    ['.cursor/hooks.json', upsertCursorHooks(read('.cursor/hooks.json'))],
    ['.devin/hooks.v1.json', upsertDevinHooks(read('.devin/hooks.v1.json'))],
    ['.codex/hooks.json', upsertCodexHooks(read('.codex/hooks.json'))],
  ];
  const written: string[] = [];
  for (const [rel, content, mode] of files) {
    const abs = path.join(gitRoot, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, mode ? { mode } : undefined);
    if (mode) fs.chmodSync(abs, mode);
    written.push(rel);
  }
  return written;
}
